[phases.setup]
nixPkgs = ["python39"]  # Используем Python 3.9

[phases.install]
commands = [
  "pip install -r requirements.txt"  # Установка зависимостей
]

[start]
command = "python app.py"  # Команда для запуска